
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer


from pathlib import Path

# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Tk, Canvas, Entry, StringVar, Text, Button, PhotoImage


OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / Path(r"C:\Users\sys73\Desktop\build\assets\frame0")


def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)



window = Tk()

window.geometry("890x650")
window.configure(bg = "#F4D6CC")


name_var=StringVar()
email_var=StringVar()
passw_var=StringVar()
grade_var=StringVar()

def submit():
    name = name_var.get()
    passw = passw_var.get()
    email = email_var.get()
    grade = grade_var.get()
    
    mycursor = mydb.cursor()

    class user:
        def __init__(self,username,password, grade, email):
            self.username=username
            self.password=password
            self.grade=grade
            self.email = email
        def store(self):
            a=(self.username,self.password,self.grade, self.email)
            query="insert into learnquest values(%s,%s,%s,%s)"
            mycursor.execute(query,a)
            mydb.commit()
        def check(self):
            exists=False
            mycursor.execute('select * from learnquest')
            a=mycursor.fetchall()
            for x in a:
                if self.username in x[0]:
                    exists=True
            return exists
        
        
    tba_user = user(name, passw ,grade, email)
    if tba_user.check() :
        print('already exist')
    else:
        tba_user.store()



canvas = Canvas(
    window,
    bg = "#F4D6CC",
    height = 650,
    width = 890,
    bd = 0,
    highlightthickness = 0,
    relief = "ridge"
)

canvas.place(x = 0, y = 0)
canvas.create_text(
    260.0,
    94.0,
    anchor="nw",
    text="Create an account",
    fill="#5F5F5F",
    font=("Poppins Regular", 40 * -1)
)

canvas.create_text(
    175.5,
    224.0,
    anchor="nw",
    text="Name",
    fill="#5F5F5F",
    font=("Poppins Regular", 16 * -1)
)

canvas.create_text(
    175.5,
    336.0,
    anchor="nw",
    text="Email",
    fill="#5F5F5F",
    font=("Poppins Regular", 16 * -1)
)

entry_image_1 = PhotoImage(
    file=relative_to_assets("entry_1.png"))
entry_bg_1 = canvas.create_image(
    292.5,
    504.0,
    image=entry_image_1
)
entry_1 = Entry(
    bd=0,
    bg="#FFFFFF",
    fg="#000716",
    highlightthickness=0,
    textvariable=name_var,
)
entry_1.place(
    x=176.0,
    y=474.0,
    width=233.0,
    height=58.0
)

canvas.create_text(
    175.5,
    454.0,
    anchor="nw",
    text="Password",
    fill="#5F5F5F",
    font=("Poppins Regular", 16 * -1)
)

button_image_1 = PhotoImage(
    file=relative_to_assets("button_1.png"))
button_1 = Button(
    image=button_image_1,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_1 clicked"),
    relief="flat"
)
button_1.place(
    x=510.0,
    y=578.0,
    width=172.18182373046875,
    height=43.085723876953125
)

button_image_2 = PhotoImage(
    file=relative_to_assets("button_2.png"))
button_2 = Button(
    image=button_image_2,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_2 clicked"),
    relief="flat"
)
button_2.place(
    x=187.5,
    y=578.0,
    width=172.18182373046875,
    height=43.085723876953125
)

button_image_3 = PhotoImage(
    file=relative_to_assets("button_3.png"))
button_3 = Button(
    image=button_image_3,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_3 clicked"),
    relief="flat"
)
button_3.place(
    x=176.0,
    y=544.0,
    width=168.40579223632812,
    height=24.347824096679688
)

canvas.create_rectangle(
    178.0,
    250.0,
    406.0,
    298.0,
    fill="#F4D6CC",
    outline="")

canvas.create_rectangle(
    178.0,
    362.0,
    406.0,
    410.0,
    fill="#F4D6CC",
    outline="")

canvas.create_rectangle(
    178.0,
    480.0,
    406.0,
    528.0,
    fill="#F4D6CC",
    outline="")

entry_image_2 = PhotoImage(
    file=relative_to_assets("entry_2.png"))
entry_bg_2 = canvas.create_image(
    292.5,
    274.0,
    image=entry_image_2
)
entry_2 = Entry(
    bd=0,
    bg="#FFFFFF",
    fg="#000716",
    highlightthickness=0,
    textvariable=grade_var,
)
entry_2.place(
    x=176.0,
    y=244.0,
    width=233.0,
    height=58.0
)

entry_image_3 = PhotoImage(
    file=relative_to_assets("entry_3.png"))
entry_bg_3 = canvas.create_image(
    292.5,
    386.0,
    image=entry_image_3
)
entry_3 = Entry(
    bd=0,
    bg="#FFFFFF",
    fg="#000716",
    highlightthickness=0,
    textvariable=email_var,
)
entry_3.place(
    x=176.0,
    y=356.0,
    width=233.0,
    height=58.0
)

entry_image_4 = PhotoImage(
    file=relative_to_assets("entry_4.png"))
entry_bg_4 = canvas.create_image(
    627.0,
    501.0,
    image=entry_image_4
)
entry_4 = Entry(
    bd=0,
    bg="#FFFFFF",
    fg="#000716",
    highlightthickness=0,
    textvariable=grade_var,
)
entry_4.place(
    x=510.5,
    y=471.0,
    width=233.0,
    height=58.0
)

canvas.create_rectangle(
    512.5,
    247.0,
    740.5,
    295.0,
    fill="#F4D6CC",
    outline="")

canvas.create_rectangle(
    512.5,
    359.0,
    740.5,
    407.0,
    fill="#F4D6CC",
    outline="")

canvas.create_rectangle(
    512.5,
    477.0,
    740.5,
    525.0,
    fill="#F4D6CC",
    outline="")

entry_image_5 = PhotoImage(
    file=relative_to_assets("entry_5.png"))
entry_bg_5 = canvas.create_image(
    627.0,
    271.0,
    image=entry_image_5
)
entry_5 = Entry(
    bd=0,
    bg="#FFFFFF",
    fg="#000716",
    highlightthickness=0,
    textvariable=passw_var,
    show='*'
)
entry_5.place(
    x=510.5,
    y=241.0,
    width=233.0,
    height=58.0
)

entry_image_6 = PhotoImage(
    file=relative_to_assets("entry_6.png"))
entry_bg_6 = canvas.create_image(
    627.0,
    383.0,
    image=entry_image_6
)
entry_6 = Entry(
    bd=0,
    bg="#FFFFFF",
    fg="#000716",
    highlightthickness=0
)
entry_6.place(
    x=510.5,
    y=353.0,
    width=233.0,
    height=58.0
)

canvas.create_text(
    512.5,
    223.0,
    anchor="nw",
    text="Grade (type no. 6 - 12)",
    fill="#5F5F5F",
    font=("Poppins Regular", 16 * -1)
)

canvas.create_text(
    512.5,
    335.0,
    anchor="nw",
    text="Electives (for 11-12)",
    fill="#5F5F5F",
    font=("Poppins Regular", 16 * -1)
)

canvas.create_text(
    512.5,
    453.0,
    anchor="nw",
    text="???",
    fill="#5F5F5F",
    font=("Poppins Regular", 16 * -1)
)
window.resizable(False, False)
window.mainloop()
