
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer


from pathlib import Path

# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage


OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / Path(r"C:\Users\sys73\Desktop\build\assets\frame2")


def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)


window = Tk()

window.geometry("890x650")
window.configure(bg = "#F4D6CC")


canvas = Canvas(
    window,
    bg = "#F4D6CC",
    height = 650,
    width = 890,
    bd = 0,
    highlightthickness = 0,
    relief = "ridge"
)

canvas.place(x = 0, y = 0)
canvas.create_text(
    260.0,
    94.0,
    anchor="nw",
    text="Create an account",
    fill="#5F5F5F",
    font=("Poppins Regular", 40 * -1)
)

entry_image_1 = PhotoImage(
    file=relative_to_assets("entry_1.png"))
entry_bg_1 = canvas.create_image(
    449.0,
    274.0,
    image=entry_image_1
)
entry_1 = Entry(
    bd=0,
    bg="#FFFFFF",
    fg="#000716",
    highlightthickness=0
)
entry_1.place(
    x=216.0,
    y=244.0,
    width=466.0,
    height=58.0
)

canvas.create_text(
    216.0,
    224.0,
    anchor="nw",
    text="Grade (type no. 6 - 12)",
    fill="#5F5F5F",
    font=("Poppins Regular", 16 * -1)
)

entry_image_2 = PhotoImage(
    file=relative_to_assets("entry_2.png"))
entry_bg_2 = canvas.create_image(
    449.0,
    386.0,
    image=entry_image_2
)
entry_2 = Entry(
    bd=0,
    bg="#FFFFFF",
    fg="#000716",
    highlightthickness=0
)
entry_2.place(
    x=216.0,
    y=356.0,
    width=466.0,
    height=58.0
)

canvas.create_text(
    216.0,
    336.0,
    anchor="nw",
    text="Electives (for 11-12)",
    fill="#5F5F5F",
    font=("Poppins Regular", 16 * -1)
)

entry_image_3 = PhotoImage(
    file=relative_to_assets("entry_3.png"))
entry_bg_3 = canvas.create_image(
    449.0,
    504.0,
    image=entry_image_3
)
entry_3 = Entry(
    bd=0,
    bg="#FFFFFF",
    fg="#000716",
    highlightthickness=0
)
entry_3.place(
    x=216.0,
    y=474.0,
    width=466.0,
    height=58.0
)

canvas.create_text(
    216.0,
    454.0,
    anchor="nw",
    text="???",
    fill="#5F5F5F",
    font=("Poppins Regular", 16 * -1)
)

button_image_1 = PhotoImage(
    file=relative_to_assets("button_1.png"))
button_1 = Button(
    image=button_image_1,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_1 clicked"),
    relief="flat"
)
button_1.place(
    x=496.0,
    y=577.0,
    width=172.18182373046875,
    height=43.085693359375
)

button_image_2 = PhotoImage(
    file=relative_to_assets("button_2.png"))
button_2 = Button(
    image=button_image_2,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_2 clicked"),
    relief="flat"
)
button_2.place(
    x=216.0,
    y=578.0,
    width=172.18182373046875,
    height=43.085693359375
)

button_image_3 = PhotoImage(
    file=relative_to_assets("button_3.png"))
button_3 = Button(
    image=button_image_3,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_3 clicked"),
    relief="flat"
)
button_3.place(
    x=216.5,
    y=540.0,
    width=168.40579223632812,
    height=24.34783935546875
)
window.resizable(False, False)
window.mainloop()
