
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer


from pathlib import Path

# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage


OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / Path(r"C:\Users\sys73\Desktop\build\assets\frame5")


def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)


window = Tk()

window.geometry("890x650")
window.configure(bg = "#F4B860")


canvas = Canvas(
    window,
    bg = "#F4B860",
    height = 650,
    width = 890,
    bd = 0,
    highlightthickness = 0,
    relief = "ridge"
)

canvas.place(x = 0, y = 0)
canvas.create_text(
    256.0,
    44.0,
    anchor="nw",
    text="POMODORO\nTIMER",
    fill="#F4D6CC",
    font=("Poppins Regular", 64 * -1)
)

canvas.create_text(
    225.0,
    325.0,
    anchor="nw",
    text="25 : 00",
    fill="#F4D6CC",
    font=("Poppins Regular", 64 * -1)
)

button_image_1 = PhotoImage(
    file=relative_to_assets("button_1.png"))
button_1 = Button(
    image=button_image_1,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_1 clicked"),
    relief="flat"
)
button_1.place(
    x=170.0,
    y=536.0,
    width=172.181884765625,
    height=43.08570861816406
)

button_image_2 = PhotoImage(
    file=relative_to_assets("button_2.png"))
button_2 = Button(
    image=button_image_2,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_2 clicked"),
    relief="flat"
)
button_2.place(
    x=548.0,
    y=536.0,
    width=172.181640625,
    height=43.08570861816406
)
window.resizable(False, False)
window.mainloop()
