
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer


from pathlib import Path

# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage


OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / Path(r"C:\Users\sys73\Desktop\build\assets\frame6")


def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)


window = Tk()

window.geometry("1155x650")
window.configure(bg = "#F4D6CC")


canvas = Canvas(
    window,
    bg = "#F4D6CC",
    height = 650,
    width = 1155,
    bd = 0,
    highlightthickness = 0,
    relief = "ridge"
)

canvas.place(x = 0, y = 0)
image_image_1 = PhotoImage(
    file=relative_to_assets("image_1.png"))
image_1 = canvas.create_image(
    577.0,
    325.0,
    image=image_image_1
)

canvas.create_text(
    83.657470703125,
    477.26849365234375,
    anchor="nw",
    text="What made you unhappy?",
    fill="#000000",
    font=("Inter Regular", 34 * -1)
)

canvas.create_text(
    68.611083984375,
    213.65740966796875,
    anchor="nw",
    text="Describe how you feel today in a word",
    fill="#000000",
    font=("Inter Regular", 40 * -1)
)

canvas.create_text(
    83.657470703125,
    335.8333435058594,
    anchor="nw",
    text="What made you happy?",
    fill="#000000",
    font=("Inter Regular", 34 * -1)
)

canvas.create_text(
    220.879638671875,
    51.15740966796875,
    anchor="nw",
    text="Mental Health Journal\n",
    fill="#000000",
    font=("Inter Regular", 65 * -1)
)

entry_image_1 = PhotoImage(
    file=relative_to_assets("entry_1.png"))
entry_bg_1 = canvas.create_image(
    859.4444580078125,
    244.95370483398438,
    image=entry_image_1
)
entry_1 = Entry(
    bd=0,
    bg="#F4D6CC",
    fg="#000716",
    highlightthickness=0
)
entry_1.place(
    x=669.861083984375,
    y=213.65740966796875,
    width=379.166748046875,
    height=60.59259033203125
)

entry_image_2 = PhotoImage(
    file=relative_to_assets("entry_2.png"))
entry_bg_2 = canvas.create_image(
    859.4444580078125,
    382.1759033203125,
    image=entry_image_2
)
entry_2 = Entry(
    bd=0,
    bg="#F4D6CC",
    fg="#000716",
    highlightthickness=0
)
entry_2.place(
    x=669.861083984375,
    y=350.8796081542969,
    width=379.166748046875,
    height=60.59259033203125
)

entry_image_3 = PhotoImage(
    file=relative_to_assets("entry_3.png"))
entry_bg_3 = canvas.create_image(
    859.4444580078125,
    508.5647888183594,
    image=entry_image_3
)
entry_3 = Entry(
    bd=0,
    bg="#F4D6CC",
    fg="#000716",
    highlightthickness=0
)
entry_3.place(
    x=669.861083984375,
    y=477.26849365234375,
    width=379.166748046875,
    height=60.59259033203125
)

button_image_1 = PhotoImage(
    file=relative_to_assets("button_1.png"))
button_1 = Button(
    image=button_image_1,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_1 clicked"),
    relief="flat"
)
button_1.place(
    x=939.49072265625,
    y=562.7315063476562,
    width=132.407470703125,
    height=45.138885498046875
)

canvas.create_text(
    928.0556640625,
    559.120361328125,
    anchor="nw",
    text="Submit",
    fill="#000000",
    font=("Inter Regular", 30 * -1)
)
window.resizable(False, False)
window.mainloop()
